config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  devise_scope :user do
    post 'custom_email', to: 'oauth_callbacks#custom_email'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # default_url_options host: '127.0.0.1'
  concern :votable do
    member do
      patch :positive_vote
      patch :negative_vote
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, only: %i[index new show create update destroy], concerns: %i[votable] do
    resources :comments, defaults: { commentable: 'questions' }
    resources :answers, shallow: true, only: %i[create update destroy], concerns: %i[votable] do
      member do
        patch :best_answer
      end
      resources :comments, defaults: { commentable: 'answers' }
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachment, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index
  get 'search', to: 'search#search'

  mount ActionCable.server => '/cable'
  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_one :reward, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user, dependent: :destroy
  belongs_to :user
  has_many :comments, dependent: :destroy, as: :commentable

  after_save :publish_question
  after_create :create_subscription

  include Linkable
  include Attachable
  include Votable

  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :body, :title, presence: true

  def best_answer
    answers.best.first
  end

  def subscribed?(user)
    subscriptions.exists?(user: user)
  end

  def subscription(user)
    subscriptions.find_by(user: user)
  end

  private

  def publish_question
    ActionCable.server.broadcast('questions',
                                 id: id,
                                 title: title)
  end

  def create_subscription
    subscriptions.create(user_id: user_id, question_id: self)
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class QuestionsController < Api::V1::BaseController
      before_action :question, only: %i[show update destroy]
      authorize_resource

      def index
        @questions = Question.all
        render json: @questions, each_serializer: QuestionsSerializer
      end

      def show
        render json: question
      end

      def create
        @question = current_resource_owner.questions.new(question_params)
        if @question.save
          head :ok
        else
          head 422
        end
      end

      def update
        if question.update(question_params)
          head :ok
        else
          head 422
        end
      end

      def destroy
        if question.destroy
          head :ok
        else
          head 422
        end
      end

      private

      def question_params
        params.require(:question).permit(:title, :body,
                                         links_attributes: %i[name url])
      end

      def question
        @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
      end
    end
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :gon_variables, only: :show
  before_action :question, except: %i[index create]

  include Voted

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    answer.links.new
  end

  def new
    question
    question.links.new
    question.build_reward
  end

  def create
    @question = current_user.questions.new(question_params)
    files_params

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    question.update(question_params)
    files_params
  end

  def destroy
    question.destroy
    flash[:delete] = 'Question successfully deleted.'
    redirect_to questions_path
  end

  private

  def gon_variables
    gon.question_id = question.id
    gon.question_owner_id = question.user.id
  end

  def answer
    @answer ||= question.answers.new
  end
  helper_method :answer

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  helper_method :question

  def answers
    @answers ||= question.reload.answers
  end

  helper_method :answers

  def question_params
    params.require(:question).permit(:title, :body,
                                     links_attributes: %i[name url],
                                     reward_attributes: %i[name img])
  end

  def files_params
    if params[:question][:files].present?
      params[:question][:files].each do |file|
        question.files.attach(file)
      end
    end
  end
end

app/views/questions/_form.slim
= form_with model: question, class: 'hidden', html: {id: "edit-question"} do |f|
  div.form-group
    p
    = f.label :title
    = f.text_area :title, class: 'form-control'
    p
      = f.label :body
      = f.text_area :body, class: 'form-control'

    ul.attachments

      =render question.files

    ul.links

      =render question.links
    p
      = f.label :files
      = f.file_field :files, multiple: true, class: 'form-control-file'
    p
      = link_to_add_association t('add_link'), f, :links, partial: 'shared/nested_links_form', 'data-association-insertion-method' => 'after', form_name: 'link'
  = f.submit class: "btn btn-primary"

app/views/questions/_question.html.slim
- cache_unless current_user.try(:admin), ['question_attrs', question] do
  h1= question.title
  p= question.body
  p= question.user.email
- cache_unless current_user.try(:admin), ['question_vote', question] do
  div id="vote-block"
     =render 'shared/votes', resource: question
div class= 'question-subscriptions-block'
   =render 'subscriptions/subscriptions', question: question
- cache_unless current_user.try(:admin), ['question_files', question] do
  -if question.files.attached?
  ul.list-group
     -question.files.each do |file|
        li class="attachment-id-#{file.id} form-control"
           = link_to file.filename, url_for(file)
- cache_unless current_user.try(:admin), ['question_links_and_comments'] do
  .links
     p Links:
     ul
        = render partial: "links/link_without_delete_link", collection: question.links, :as => :link
  .question_comments
     -if question.comments.exists?
        ul.list-group
        =render question.comments
     -else
        span.text-secondary.empty style='font-size: 10pt' 0 comment's
- if signed_in?
   = content_tag(:span, class: 'text-primary comment-button', style: 'font-size: 8pt')
      = link_to t('add comment'), '', class: 'add_comment_button', style: 'text-decoration: none;', remote: true

   =render 'comments/form', resource: question
- cache_unless current_user.try(:admin), ['question_reward', question] do
  #reward
     p Reward:

     -if question.reward
        = question.reward.name
        = image_tag(url_for(question.reward.img), size: 200)
-if %i[edit destroy].any? { |action| can? action, question }
   = button_to t('.delete'), question_path(question), method: :delete, class: "btn btn-outline-danger"
   p= link_to t('.edit'), '#', class: 'edit-question-link btn btn-outline-warning'
   =render 'form'
#question-errors

app/views/questions/best_answer.js.erb
$('#question-errors').html('<%= render 'shared/errors', resource: question %>');
<% unless question.errors.present? %>
$('#question').html('<%= j render question %>');
<% end %>

app/views/questions/index.html.slim
ul.list-group.question_list
  p.btn
    =link_to t('.question.new_button'), new_question_path, class: "text-success"
  - cache_unless current_user.try(:admin), @questions.cache_key do
    -@questions.each do |question|
      p.list-group-item.list-group-item-action
        =link_to question.title, question_path(question)

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question
= form_with model: @question, local: true do |f|
  div.form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
    p
    = f.label :body
    = f.text_area :body, class: 'form-control'
    p
    = f.label :files
    = f.file_field :files, multiple: true, class: 'form-control-file'
    = link_to_add_association t('add_link'), f, :links, partial: 'shared/nested_links_form', 'data-association-insertion-method' => 'after', form_name: 'link'
    p
    = f.fields_for :reward do |reward|
      = reward.label :name, t('Reward Name')
      = reward.text_area :name, class: 'form-control'
      p
      = reward.label :img, t('Reward Image')
      = reward.file_field :img, class: 'form-control-file'
    .links

    = f.submit class: "btn btn-primary"

app/views/questions/show.html.slim
div#question
  =render question
br=
.answers
    = render question.answers.unscoped.order_by_best
= render 'answers/form'

app/views/questions/subscribe.js.erb
$('.question-subscriptions-block').html('<%= j render 'shared/subscriptions', resource: question %>');

app/views/questions/unsubscribe.js.erb
$('.question-subscriptions-block').html('<%= j render 'shared/subscriptions', resource: question %>');

app/views/questions/update.js.erb
$('#question-errors').html('<%= render 'shared/errors', resource: question %>');
<% unless question.errors.present? %>
$('#question').html('<%= j render 'questions/question' %>');
<% end %>