config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  devise_scope :user do
    post 'custom_email', to: 'oauth_callbacks#custom_email'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # default_url_options host: '127.0.0.1'
  concern :votable do
    member do
      patch :positive_vote
      patch :negative_vote
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, only: %i[index new show create update destroy], concerns: %i[votable] do
    resources :comments, defaults: { commentable: 'questions' }
    resources :answers, shallow: true, only: %i[create update destroy], concerns: %i[votable] do
      member do
        patch :best_answer
      end
      resources :comments, defaults: { commentable: 'answers' }
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachment, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index
  get 'search', to: 'search#search'

  mount ActionCable.server => '/cable'
  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question, touch: true
  belongs_to :user
  has_many :comments, dependent: :destroy, as: :commentable

  after_commit :publish_answer, :send_notification

  include Linkable
  include Attachable
  include Votable

  validates :body, presence: true
  validates :body, length: { minimum: 6 }

  scope :best, -> { where(best_answer: true) }
  scope :order_by_best, -> { order(best_answer: :desc) }

  def make_best_answer
    Answer.transaction do
      user.id == question.reward&.user&.id && id == question.best_answer&.id ? question.reward&.update!(user: nil) : question.reward&.update!(user: user)
      question.best_answer&.update!(best_answer: false)
      update!(best_answer: true)
    end
  end

  private

  def publish_answer
    ActionCable.server.broadcast("answers_for_question_#{question.id}",
                                 author: user.email,
                                 rating: rating,
                                 links: links,
                                 answer: self)
  end

  def send_notification
    NewAnswerNotificationJob.perform_later(self) if question.subscriptions.exists?
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :answer, except: %i[new show edit]
  include Voted

  authorize_resource

  def create
    answer.user = current_user
    answer.save
    files_params
  end

  def new; end

  def show; end

  def edit; end

  def update
    answer.update(answer_params)
    files_params
  end

  def destroy
    answer.destroy
    flash[:delete] = 'Answer successfully deleted.'
  end

  def best_answer
    authorize! :best_answer, answer
    answer.make_best_answer
  end

  private

  def answer
    @answer ||= params[:id] ? Answer.with_attached_files.find(params[:id]) : answers.build(answer_params)
  end
  helper_method :answer

  def answers
    @answers ||= question.reload.answers
  end
  helper_method :answers

  def answer_params
    params.require(:answer).permit(:body,
                                   links_attributes: %i[name url])
  end

  def question
    @question = Question.with_attached_files.find(params[:question_id])
  end
  helper_method :question

  def files_params
    if params[:answer][:files].present?
      params[:answer][:files].each do |file|
        answer.files.attach(file)
      end
    end
  end
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class AnswersController < Api::V1::BaseController
      before_action :answer, only: %i[show update destroy]
      before_action :answers, only: %i[index create]

      authorize_resource

      def index
        render json: answers, each_serializer: AnswersSerializer
      end

      def show
        render json: answer
      end

      def create
        authorize! :create, question

        @answer = question.answers.new(answer_params)
        @answer.user = current_resource_owner
        if @answer.save
          head :ok
        else
          head 422
        end
      end

      def update
        if answer.update(answer_params)
          head :ok
        else
          head 422
        end
      end

      def destroy
        if answer.destroy
          head :ok
        else
          head 422
        end
      end

      private

      def answers
        @answers ||= question.reload.answers
      end

      def answer
        @answer ||= params[:id] ? Answer.with_attached_files.find(params[:id]) : answers.build(answer_params)
      end

      def answer_params
        params.require(:answer).permit(:body,
                                       links_attributes: %i[name url])
      end

      def question
        @question = Question.with_attached_files.find(params[:question_id])
      end
    end
  end
end

app/views/answers/_answer.html.slim
ul.list-group id="answer-id-#{answer.id}"

  -if answer.best_answer?
    div#best-answer
      = answer.body
  - else
    div
      = answer.body
  div id="vote-block"
    = render 'shared/votes', resource: answer
  .links
    p Links:
    ul
      = render partial: "links/link_without_delete_link", collection: answer.links, :as => :link
  .answer_comments

    - if answer.comments.exists?
      = render answer.comments
    - else
      span.text-secondary.empty style='font-size: 10pt' 0 comment's
  - if signed_in?
    = content_tag(:span, class: 'text-primary comment-button', style: 'font-size: 8pt')
      = link_to t('add comment'), '', class: 'add_comment_button', style: 'text-decoration: none;', remote: true, data: {answer_id: answer.id}
    =render 'comments/form', resource: answer
  ul.list-group
    -answer.files.each do |file|
      li class="attachment-id-#{file.id} list-group-item list-group-item-action"
        = link_to file.filename, url_for(file)

    p.btn.btn-outline-info
      =answer.user.email

  -if %i[update destroy].any? { |action| can? action, answer } # analogue of current_user && current_user.author_of? but there are nuances
    = button_to t('delete_answer'), answer_path(answer), method: :delete, remote: true, class: 'btn btn-outline-danger'
    p= link_to t('edit_answer'), '#', class: 'edit-answer-link btn btn-outline-warning', data: { answer_id: answer.id }

    = form_with model: answer, class: 'hidden', html: {id: "edit-answer-#{answer.id}"} do |f|
      p.list-group
      = f.label :body, 'Your answer'
      = f.text_area :body, class: 'form-control'
      ul.attachments
        = render answer.files
      = f.label :files
      = f.file_field :files, multiple: true
      ul.links

        = render answer.links
      p
        = link_to_add_association t('add_link'), f, :links, partial: 'shared/nested_links_form', 'data-association-insertion-method' => 'after', form_name: 'link'
        ul.links

      = f.submit class: "btn btn-primary"

  -if can? :best_answer, answer
    p= link_to t('.best'), best_answer_answer_path(answer), class: 'best-answer-link btn btn-dark', method: :patch , remote: true

  .answer-errors

app/views/answers/_form.slim
.new-answer-errors
  = render 'shared/errors', resource: answer
= form_with model: [question, answer], class: 'new-answer' do |f|

  div.form-group
    p
    = f.label :body
    = f.text_area :body, class: 'form-control'
    p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true, class: 'form-control-file'
    = link_to_add_association t('add_link'), f, :links, partial: 'shared/nested_links_form', 'data-association-insertion-method' => 'after', form_name: 'link',
     force_non_association_create: true
    ul.links
    = f.submit class: "btn btn-primary"

app/views/answers/best_answer.js.erb
$('.answers').html('<%= j render answer.question.answers.unscoped.order_by_best %>')

app/views/answers/create.js.erb
$('.new-answer-errors').html('<%= render 'shared/errors', resource: answer %>')
<% if answer.persisted? %>
$('.answers').append('<%= j render answer %>')
$(' .new-answer #answer_body').val('');
$('.form-control-file').val('');
$('.form-control-file').attr('disabled', false);
<%end %>

app/views/answers/destroy.js.erb
<% unless answer.persisted? %>
$('.notice').html('<%= render 'shared/flash' %>')
$("#answer-id-<%= answer.id %>").fadeOut("slow").remove()
<%end %>

app/views/answers/update.js.erb
$('<%= "#answer-id-#{answer.id} .answer-errors" %>').html('<%= render 'shared/errors', resource: answer %>');
<% unless answer.errors.present? %>
$('<%= "#answer-id-#{answer.id}" %>').replaceWith('<%= j render answer %>');
<% end %>