config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  devise_scope :user do
    post 'custom_email', to: 'oauth_callbacks#custom_email'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # default_url_options host: '127.0.0.1'
  concern :votable do
    member do
      patch :positive_vote
      patch :negative_vote
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, only: %i[index new show create update destroy], concerns: %i[votable] do
    resources :comments, defaults: { commentable: 'questions' }
    resources :answers, shallow: true, only: %i[create update destroy], concerns: %i[votable] do
      member do
        patch :best_answer
      end
      resources :comments, defaults: { commentable: 'answers' }
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachment, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index
  get 'search', to: 'search#search'

  mount ActionCable.server => '/cable'
  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :user_id, uniqueness: { scope: :question_id }
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :question, only: :create
  before_action :subscription, only: :destroy

  authorize_resource

  def create
    question.subscriptions.create(user_id: current_user.id)
  end

  def destroy
    @question = subscription.question
    subscription.destroy
  end

  private

  def question
    @question = Question.find(params[:question_id])
  end
  helper_method :question

  def subscription
    @subscription = Subscription.find(params[:id])
  end
end

app/views/subscriptions/_subscriptions.html.slim
.subscriptions
  -if current_user
    -if question.subscribed?(current_user)
      = button_to t('unsubscribe'), subscription_path(question.subscription(current_user)), remote: true, method: :delete, data: { type: :js }
    -else
      = button_to t('subscribe'), question_subscriptions_path(question), remote: true, data: { type: :js }

app/views/subscriptions/create.js.erb
$('.question-subscriptions-block').html('<%= j render 'subscriptions', question: question %>');

app/views/subscriptions/destroy.js.erb
$('.question-subscriptions-block').html('<%= j render 'subscriptions', question: @question %>');